#!/bin/bash
#
#read inputs
echo "Program to compare numbers"
echo "Enter first number"
read X
echo "Enter 2nd number"
read Y
if [ "$X" -lt "$Y" ]
then
echo "$X is less than $Y"
elif [ $X -gt $Y ]
then
echo "$X is greater than $Y"
else 
echo "$X is equal to $Y"
fi
